---
language: node_js
sudo: false
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run doc
deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/publish-npm
